<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Log extends CI_Controller
{

      var $API ="";
    
    public function __construct()
    {
          parent::__construct();
          $this->load->model('Mlog');
          $this->load->library('form_validation');
          $this->load->library('curl');
          $this->id_pengguna=$this->session->userdata('tax_pengguna');
 
    }

    private function cekAkses($var=null){
        return cek($this->id_pengguna,$var);
    }

    public function index()
    {
        $akses =$this->cekAkses(uri_string());
        if(isset($_POST['nama_wp']) && $_POST['nama_wp'] != ''){
            $nama_wp = $_POST['nama_wp'];
        }else{
            $nama_wp = 'all';
        }

        $log = $this->Mlog->getdata($nama_wp);

        $data = array(
            'nama_wp'   => $nama_wp, 
            'log'     => $log,
        );

        $this->template->load('blank','log/Log_list', $data);
    }

    public function cetak_laporan(){
        $bulan = $this->uri->segment('3');
        $tahun = $this->uri->segment('4');
        $nama_wp = $this->uri->segment('5');

        $rekap = $this->Mrekap->getdata($bulan, $tahun, $nama_wp);
      
        $data = array(
            'tanggal'   => date('F', strtotime($bulan)).' '.$tahun,
            'waktu'   => date('dmYHis'),
            'bulan' => $bulan,
            'tahun' => $tahun,
            'nama_wp' => $nama_wp,
            'rekap'   => $rekap,
            
        );
        
            // $this->template->load('blank','transaksi/Transaksi_list', $data);/
            $this->load->view('rekap/cetakRekapBulanan', $data)    ;
    }
 
}

/* End of file Transaksi.php */
/* Location: ./application/controllers/Transaksi.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-12-12 08:37:45 */
/* http://harviacode.com */