<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Refclient extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Mclient');
        $this->load->library('form_validation');
        $this->db2 = $this->load->database('pdrd2', TRUE);
        $this->id_pengguna=$this->session->userdata('tax_pengguna');
        $connected = $this->db2->initialize();

        if (!$connected) {
            echo 'Tidak Dapat Mengambil Data Dari Server. <a href="javascript:history.back()">Kembali Halaman Sebelumnya</a> ';
        }
    }

    private function cekAkses($var=null){
        return cek($this->id_pengguna,$var);
    }

    public function index()
    {

        //$refclient = $this->Mclient->get_all();
        //$akses =$this->cekAkses(uri_string()); 
        $refclient = $this->Mclient->get_all_baru();

        $data = array(
            'refclient_data' => $refclient
        );

        //echo count($refclient);

        //$this->template->load('blank','refclient/Refclient_list', $data);
        $this->template->load('blank','refclient/Refclient_list_baru', $data);
        
    }


    public function create() 
    {
        $data = array(
            'button' => 'Form Tambah',
            'action' => site_url('refclient/create_action'),
	    'kd_client' => set_value('kd_client'),
	    'nama_wp' => set_value('nama_wp'),
	    'email' => set_value('email'),
        'npwp'=>set_value('npwp')
	);
        $this->template->load('blank','refclient/Refclient_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama_wp' => $this->input->post('nama_wp',TRUE),
		'email' => $this->input->post('email',TRUE),
        'npwp'=>$this->input->post('npwp',true)
	    );

           $this->Mclient->insert($data);
            
            redirect(site_url('refclient'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Mclient->get_by_id($id);

        if ($row) {
            $data = array(
                'button'    => 'Form Edit',
                'action'    => site_url('refclient/update_action'),
                'kd_client' => set_value('kd_client', $row->kd_client),
                'nama_wp'   => set_value('nama_wp', $row->nama_wp),
                'email'     => set_value('email', $row->email),
                'npwp'      =>set_value('npwp',$row->npwp)
	    );
            $this->template->load('blank','refclient/Refclient_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('refclient'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('kd_client', TRUE));
        } else {
            $data = array(
            'nama_wp' => $this->input->post('nama_wp',TRUE),
            'email'   => $this->input->post('email',TRUE),
            'npwp'    =>$this->input->post('npwp',true)
	    );

            $this->Mclient->update($this->input->post('kd_client', TRUE), $data);
            
            redirect(site_url('refclient'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Mclient->get_by_id($id);

        if ($row) {
            $this->Mclient->delete($id);
            
            
            redirect(site_url('refclient'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('refclient'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama_wp', 'nama wp', 'trim|required');
    $this->form_validation->set_rules('npwp', 'npwp', 'trim|required');
	$this->form_validation->set_rules('email', 'email', 'trim|required');

	$this->form_validation->set_rules('kd_client', 'kd_client', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Refclient.php */
/* Location: ./application/controllers/Refclient.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-12-12 08:10:16 */
/* http://harviacode.com */