<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Refjenispajak extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Mjpajak');
        $this->load->library('form_validation');
          $this->id_pengguna=$this->session->userdata('tax_pengguna');
    }

    private function cekAkses($var=null){
        return cek($this->id_pengguna,$var);
    }

    public function index()
    {
        $akses =$this->cekAkses(uri_string());
        $refjenispajak = $this->Mjpajak->get_all();

        $data = array(
            'refjenispajak_data' => $refjenispajak
        );

        $this->template->load('blank','refjenispajak/Refjenispajak_list', $data);
    }

    

    public function create() 
    {
        $data = array(
            'button' => 'Form Tambah',
            'action' => site_url('refjenispajak/create_action'),
	    'kd_jenispajak' => set_value('kd_jenispajak'),
	    'rekening' => set_value('rekening'),
	    'nama_pajak' => set_value('nama_pajak'),
	);
        $this->template->load('blank','refjenispajak/Refjenispajak_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'rekening' => $this->input->post('rekening',TRUE),
		'nama_pajak' => $this->input->post('nama_pajak',TRUE),
	    );

           $this->Mjpajak->insert($data);
            
            redirect(site_url('refjenispajak'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Mjpajak->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Form Edit',
                'action' => site_url('refjenispajak/update_action'),
		'kd_jenispajak' => set_value('kd_jenispajak', $row->kd_jenispajak),
		'rekening' => set_value('rekening', $row->rekening),
		'nama_pajak' => set_value('nama_pajak', $row->nama_pajak),
	    );
            $this->template->load('blank','refjenispajak/Refjenispajak_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('refjenispajak'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('kd_jenispajak', TRUE));
        } else {
            $data = array(
		'rekening' => $this->input->post('rekening',TRUE),
		'nama_pajak' => $this->input->post('nama_pajak',TRUE),
	    );

            $this->Mjpajak->update($this->input->post('kd_jenispajak', TRUE), $data);
            
            redirect(site_url('refjenispajak'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Mjpajak->get_by_id($id);

        if ($row) {
            $this->Mjpajak->delete($id);
            
            
            redirect(site_url('refjenispajak'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('refjenispajak'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('rekening', 'rekening', 'trim|required');
	$this->form_validation->set_rules('nama_pajak', 'nama pajak', 'trim|required');

	$this->form_validation->set_rules('kd_jenispajak', 'kd_jenispajak', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Refjenispajak.php */
/* Location: ./application/controllers/Refjenispajak.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-12-12 08:09:55 */
/* http://harviacode.com */