<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Rekap extends CI_Controller
{

      var $API ="";
    
    public function __construct()
    {
          parent::__construct();
          $this->load->model('Mrekap');
          $this->load->library('form_validation');
          $this->load->library('curl');
          $this->id_pengguna=$this->session->userdata('tax_pengguna');
 
    }

     private function cekAkses($var=null){
        return cek($this->id_pengguna,$var);
    }

    public function index()
    {
        $akses =$this->cekAkses(uri_string()); 
        // $transaksi = $this->Mtransaksi->getdatabynow();
        if(isset($_POST['bulan'])){
            $bulan=$_POST['bulan'];
        }else{
            $bulan=date('m');
        }

        if(isset($_POST['tahun'])){
            $tahun=$_POST['tahun'];
        }else{
            $tahun=date('Y');
        }

        if(isset($_POST['nama_wp']) && $_POST['nama_wp'] != ''){
            $nama_wp = $_POST['nama_wp'];
        }else{
            $nama_wp = 'all';
        }


        $ref_bulan = array(
            '01' => 'Januari',
            '02' => 'Februari',
            '03' => 'Maret',
            '04' => 'April',
            '05' => 'Mei',
            '06' => 'Juni',
            '07' => 'Juli',
            '08' => 'Agustus',
            '09' => 'September',
            '10' => 'Oktober',
            '11' => 'November',
            '12' => 'Desember'
        );


        $rekap = $this->Mrekap->getdata($bulan, $tahun, $nama_wp);
        
        $total=0;
        foreach ($rekap as $res) {
            $total += $res->omset;
        }

        $data = array(
            'nama_wp' => $nama_wp,
            'bulan'=>$bulan,
            'tahun'=>$tahun,    
            'rekap' => $rekap,
            'total' => $total,
            'ref_bulan' => $ref_bulan,
        );

        $this->template->load('blank','rekap/Rekap_bulanan_list', $data);
    }

    function ajaxdatarekapbulanan(){
        // echo "halaman auto refresh setiap 5 detik: ".rand(99,2); //Hanya contoh saja..
        
        $bulan = $this->uri->segment('3');
        $tahun = $this->uri->segment('4');
        $nama_wp = $this->uri->segment('5');

        $rekap = $this->Mrekap->getdata($bulan, $tahun, $nama_wp);

        $total;
        foreach ($rekap as $res) {
            $total += $res->omset;
        }

        $data = array(
             'bulan'=>$bulan,
             'tahun'=>$tahun,  
             'total' => $total,
             'rekap' => $rekap,
        );

        $this->load->view('rekap/kontenajaxrekapbulanan',$data);
    }


    public function cetak_laporan(){
         
        $bulan = $this->uri->segment('3');
        $tahun = $this->uri->segment('4');
        $nama_wp = $this->uri->segment('5');

        $rekap = $this->Mrekap->getdata($bulan, $tahun, $nama_wp);
      
        $data = array(
            'tanggal'   => date('F', strtotime($bulan)).' '.$tahun,
            'waktu'   => date('dmYHis'),
            'bulan' => $bulan,
            'tahun' => $tahun,
            'nama_wp' => $nama_wp,
            'rekap'   => $rekap,
            
        );
        
            // $this->template->load('blank','transaksi/Transaksi_list', $data);/
            $this->load->view('rekap/cetakRekapBulanan', $data)    ;
    }

    public function ajaxDetail()
    {
        $tgl = date('Y-m-d', strtotime($_POST['tanggal']));
        $namawp = $_POST['namawp'];

        $res = $this->db->query("SELECT * FROM tb_transaksi_dept WHERE DATE(tgl_transaksi)='$tgl' AND nama_wp='$namawp' ORDER BY DATE(tgl_transaksi) DESC")->result();

        $total=0;
        foreach ($res as $a) {
            $total+=$a->jumlah;
        }

        $data = array(
            'res' => $res,
            'total' => $total,
            'tanggal' => $_POST['tanggal']
        );


        $this->load->view('rekap/maps/detail',$data);
    }
 
}

/* End of file Transaksi.php */
/* Location: ./application/controllers/Transaksi.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-12-12 08:37:45 */
/* http://harviacode.com */