<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mlog extends CI_Model
{

    public $table = 'tb_log';
    public $tgl = 'insert_date';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    function getdata($nama_wp)
    {
        if($nama_wp !='all'){
            $this->db->where('nama_wp', $nama_wp);
        }
        $this->db->order_by($this->tgl, $this->order);
        return $this->db->get($this->table)->result();
    }
    

}

/* End of file Mtransaksi.php */
/* Location: ./application/models/Mtransaksi.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-12-12 08:37:45 */
/* http://harviacode.com */